global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'mlapi'
    environment: 'development'

scrape_configs:
  - job_name: 'mlapi'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics/'
    scrape_interval: 15s
    scrape_timeout: 10s

